### ISSUE TITLE
If you made a commit, add your name to the AUTHORS file

### ISSUE THREAD

**Issue by fintler** [hpc/fileutils#12]
If you've written code or documentation and have committed it to the repo, please add your name to the AUTHORS file. A single line of code is enough to have your name in the AUTHORS file.

Please list it in alphabetical order.

If you have a first and last name, please keep the file in this format:

> Lastname, Firstname <email@address.with.brackets>

Otherwise, put it in whatever format you feel is right.

This issue may be closed after the following folks are listed or have confirmed that they don't want their name listed:

- [x] @jlafon 
- [x] @adammoody 
- [x] @fintler
- [ ] @fwang2 
- [x] @ddn-lixi 
- [x] @tgroff234 
- [ ] @fullerdj

**Comment by adammoody** [comment]
Feiyi is in there, and I just added Doug, so we're up-to-date here.
