### ISSUE TITLE
LICENSE file needs to be updated with release info.

### ISSUE THREAD

**Issue by fintler** [hpc/fileutils#16]
Currently, we need some kind of confirmation from the folks at the following locations that this is ok to release.

- [x] LANL
- [ ] LLNL
- [x] ORNL
- [x] DDN Japan

Please add anyone to this list who may need something added to the LICENSE file before a public release.

**Comment by adammoody** [comment]
LICENSE is up to date and code is now public!

**Comment by jlafon** [comment]
Fantastic!
